// <auto-generated />
using System;
using GabsHybridApp.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GabsHybridApp.Web.Migrations
{
    [DbContext(typeof(HybridAppDbContext))]
    partial class HybridAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("GabsHybridApp")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GabsHybridApp.Shared.Models.BackupRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BackupType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Sha256Checksum")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceFormFactor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourcePlatform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TableBreakdownJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalRecordsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BackupRecords", "GabsHybridApp");
                });

            modelBuilder.Entity("GabsHybridApp.Shared.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NavigateToUrl")
                        .HasColumnType("text");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", "GabsHybridApp");
                });

            modelBuilder.Entity("GabsHybridApp.Shared.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DeliveredDateUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("OrderDateUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ShippedDateUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders", "GabsHybridApp");
                });

            modelBuilder.Entity("GabsHybridApp.Shared.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProductUnit")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", "GabsHybridApp");
                });

            modelBuilder.Entity("GabsHybridApp.Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PictureFilename")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products", "GabsHybridApp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Original scent, 64 loads",
                            Name = "Tide Laundry Detergent",
                            Unit = "bottle",
                            UnitPrice = 350.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Size 4, 120 count",
                            Name = "Pampers Diapers",
                            Unit = "box",
                            UnitPrice = 999.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "With 1 blade cartridge",
                            Name = "Gillette Fusion Razor",
                            Unit = "pack",
                            UnitPrice = 199.75m
                        },
                        new
                        {
                            Id = 4,
                            Description = "4 bars, moisturizing cream",
                            Name = "Dove Beauty Bar",
                            Unit = "pack",
                            UnitPrice = 75.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Real, 30 oz",
                            Name = "Hellmann's Mayonnaise",
                            Unit = "jar",
                            UnitPrice = 120.00m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Phoenix scent, 4 oz",
                            Name = "Axe Body Spray",
                            Unit = "bottle",
                            UnitPrice = 190.00m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Classic, 12 oz",
                            Name = "Nescafe Instant Coffee",
                            Unit = "jar",
                            UnitPrice = 170.00m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Milk chocolate, 1.5 oz",
                            Name = "KitKat Chocolate Bar",
                            Unit = "bar",
                            UnitPrice = 30.00m
                        },
                        new
                        {
                            Id = 9,
                            Description = "24-pack, 16.9 oz bottles",
                            Name = "Nestle Pure Life Water",
                            Unit = "pack",
                            UnitPrice = 180.00m
                        },
                        new
                        {
                            Id = 10,
                            Description = "1 Liter bottle of Coca-Cola",
                            Name = "Coca-Cola 1 Liter",
                            Unit = "bottle",
                            UnitPrice = 30.00m
                        },
                        new
                        {
                            Id = 11,
                            Description = "12 fl oz can of Sprite",
                            Name = "Sprite 12 oz",
                            Unit = "can",
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Orange juice with pulp, 16.9 fl oz bottle",
                            Name = "Minute Maid Pulpy Orange",
                            Unit = "bottle",
                            UnitPrice = 25.00m
                        },
                        new
                        {
                            Id = 13,
                            Description = "750ml",
                            Name = "Tanduay White Rum",
                            Unit = "bottle",
                            UnitPrice = 125.375m
                        },
                        new
                        {
                            Id = 14,
                            Description = "1000ml",
                            Name = "Red Horse Beer",
                            Unit = "bottle",
                            UnitPrice = 118.0625m
                        },
                        new
                        {
                            Id = 15,
                            Description = "1L blended premium brandy",
                            Name = "Emperador Light",
                            Unit = "bottle",
                            UnitPrice = 165.442m
                        });
                });

            modelBuilder.Entity("GabsHybridApp.Shared.Models.RegisteredDevice", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AssignedLocation")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSyncUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("RegisteredDevices", "GabsHybridApp");
                });

            modelBuilder.Entity("GabsHybridApp.Shared.Models.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("Roles")
                        .HasColumnType("text");

                    b.Property<string>("ServerSalt")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts", "GabsHybridApp");
                });

            modelBuilder.Entity("GabsHybridApp.Shared.Models.Notification", b =>
                {
                    b.HasOne("GabsHybridApp.Shared.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GabsHybridApp.Shared.Models.OrderItem", b =>
                {
                    b.HasOne("GabsHybridApp.Shared.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GabsHybridApp.Shared.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GabsHybridApp.Shared.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
